export const BODY_LOCALITY_MAX_ADJACENT_GAP = 30;
export const BODY_LOCALITY_STRONG_ADJACENT_GAP = 15;
export const BODY_LOCALITY_MAX_HEAD_TAIL_SPAN = 160;
export const BODY_LOCALITY_TIGHTNESS_EXPONENT = 0.75;
