import builtins from "builtin-modules";
import esbuild from "esbuild";
import esbuildSvelte from "esbuild-svelte";
import * as fsUtil from "fs";
import { copyFileSync, existsSync, mkdirSync } from "fs"; // 新增导入
import * as pathUtil from "path";
import process from "process";
import sveltePreprocess from "svelte-preprocess";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;
const prod = process.argv[2] === "production";

// function debounce(delay, func) {
// 	let timeoutId;

// 	return (...args) => {
// 		clearTimeout(timeoutId);
// 		timeoutId = setTimeout(() => func(...args), delay);
// 	};
// }

// // 这里会多次使用esbuild进行编译，防止多次同时复制
// let hasCopied = false;
// function copyFile(src, dest) {
// 	if (hasCopied) {
// 		hasCopied = false;
// 		// 跳过偶数次复制
// 		return;
// 	}
// 	hasCopied = true;
// 	fsUtil.copyFile(src, dest, (err) => {
// 		const formattedTime = new Date().toLocaleTimeString("en-US", {
// 			hour12: false,
// 			hour: "2-digit",
// 			minute: "2-digit",
// 			second: "2-digit",
// 		});
// 		if (err) {
// 			console.error(`Error copying ${src}:`, err, `  - ${formattedTime}`);
// 		} else {
// 			console.log(`Copied ${src} to ${dest}`, `  - ${formattedTime}`);
// 		}
// 	});
// }

// const copyFileDebounced = debounce(1000, copyFile);

// const filesToCopy = ["./assets/styles.css", "./assets/manifest.json"];
// // 监听特定文件的变化
// filesToCopy.forEach((file) => {
// 	fsUtil.watch(file, (eventType, filename) => {
// 		if (eventType === "change") {
// 			copyFileDebounced(file, `./${filename}`);
// 		}
// 	});
// });

// // for the first time `pnpm dev`
// if (!prod) {
// 	filesToCopy.forEach((file) => {
// 		const destination = `./${pathUtil.basename(file)}`;
// 		copyFile(file, destination);
// 		// 避免被这个变量影响，导致偶数文件无法复制
// 		hasCopied = false;
// 	});
// }

async function printFilesSize(directory) {
    console.log(`Printing file sizes in directory: ${directory}`);
    try {
        const files = await fsUtil.promises.readdir(directory);
        for (const file of files) {
            const filePath = pathUtil.join(directory, file);
            const stats = await fsUtil.promises.stat(filePath);
            console.log(`${file}: ${(stats.size / 1024).toFixed(2)} KB`);
        }
    } catch (err) {
        console.error(err);
    }
}

const DIST_PATH = "dist";
const DEV_COMMAND_REGISTRY_STUB_PATH = pathUtil.resolve(
    "src/services/obsidian/command-registry.noop.ts",
);
// 根据环境决定输出位置：生产环境去 dist，开发环境留根目录
const outDir = prod ? DIST_PATH : "./";

if (prod && !existsSync(DIST_PATH)) {
    mkdirSync(DIST_PATH, { recursive: true });
}

const esbuildConfig = {
    banner: {
        js: banner,
    },
    entryPoints: {
        main: "src/main.ts",
        "cs-search-worker": "src/web-workers/server.ts",
    },
    bundle: true,
    minify: prod,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins,
        "tests/*", // 不打包测试文件夹
    ],
    format: "cjs",
    platform: "node",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outdir: outDir, 
    define: {
        "process.env.NODE_ENV": prod ? '"production"' : '"development"',
        __DEV__: prod ? "false" : "true",
    },
    plugins: [
        prod && {
            name: "alias-dev-command-registry",
            setup(build) {
                build.onResolve({ filter: /command-registry\.dev$/ }, () => {
                    return { path: DEV_COMMAND_REGISTRY_STUB_PATH };
                });
            },
        },
        esbuildSvelte({
            compilerOptions: { css: true },
            preprocess: sveltePreprocess(),
        }),
    ].filter(Boolean),
};

const context = await esbuild.context(esbuildConfig);

if (prod) {
    // 生产环境构建逻辑
    await context.rebuild();
    
    // 自动将根目录的资源复制到 dist 文件夹，方便 GitHub Release 直接打包
    const filesToCopy = ["manifest.json", "styles.css"];
    for (const file of filesToCopy) {
        if (existsSync(file)) {
            copyFileSync(file, pathUtil.join(DIST_PATH, file));
            console.log(`📑 Copied ${file} to ${DIST_PATH}/`);
        }
    }

    await printFilesSize(DIST_PATH);
    await context.dispose();
    process.exit(0);
} else {
    // 开发环境：直接监听并生成到根目录
    console.log("\n🚀 Development mode: output to root");
    await context.watch();
}
