import builtins from "builtin-modules";
import esbuild from "esbuild";
import esbuildSvelte from "esbuild-svelte";
import * as fsUtil from "fs";
import { copyFileSync, existsSync, mkdirSync } from "fs"; // 新增导入
import * as pathUtil from "path";
import process from "process";
import sveltePreprocess from "svelte-preprocess";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;
const prod = process.argv[2] === "production";
const analyzeBundle =
    process.argv.includes("--analyze") || process.env.CS_BUNDLE_ANALYZE === "1";

// function debounce(delay, func) {
// 	let timeoutId;

// 	return (...args) => {
// 		clearTimeout(timeoutId);
// 		timeoutId = setTimeout(() => func(...args), delay);
// 	};
// }

// // 这里会多次使用esbuild进行编译，防止多次同时复制
// let hasCopied = false;
// function copyFile(src, dest) {
// 	if (hasCopied) {
// 		hasCopied = false;
// 		// 跳过偶数次复制
// 		return;
// 	}
// 	hasCopied = true;
// 	fsUtil.copyFile(src, dest, (err) => {
// 		const formattedTime = new Date().toLocaleTimeString("en-US", {
// 			hour12: false,
// 			hour: "2-digit",
// 			minute: "2-digit",
// 			second: "2-digit",
// 		});
// 		if (err) {
// 			console.error(`Error copying ${src}:`, err, `  - ${formattedTime}`);
// 		} else {
// 			console.log(`Copied ${src} to ${dest}`, `  - ${formattedTime}`);
// 		}
// 	});
// }

// const copyFileDebounced = debounce(1000, copyFile);

// const filesToCopy = ["./assets/styles.css", "./assets/manifest.json"];
// // 监听特定文件的变化
// filesToCopy.forEach((file) => {
// 	fsUtil.watch(file, (eventType, filename) => {
// 		if (eventType === "change") {
// 			copyFileDebounced(file, `./${filename}`);
// 		}
// 	});
// });

// // for the first time `pnpm dev`
// if (!prod) {
// 	filesToCopy.forEach((file) => {
// 		const destination = `./${pathUtil.basename(file)}`;
// 		copyFile(file, destination);
// 		// 避免被这个变量影响，导致偶数文件无法复制
// 		hasCopied = false;
// 	});
// }

async function printFilesSize(directory) {
    console.log(`Printing file sizes in directory: ${directory}`);
    try {
        const files = await fsUtil.promises.readdir(directory);
        for (const file of files) {
            const filePath = pathUtil.join(directory, file);
            const stats = await fsUtil.promises.stat(filePath);
            console.log(`${file}: ${(stats.size / 1024).toFixed(2)} KB`);
        }
    } catch (err) {
        console.error(err);
    }
}

function formatBytes(bytes) {
    if (bytes < 1024) {
        return `${bytes} B`;
    }

    return `${(bytes / 1024).toFixed(2)} KB`;
}

async function writeBundleAnalysis(metafile) {
    if (!metafile) {
        return;
    }

    const metafilePath = pathUtil.join(DIST_PATH, "metafile.json");
    const analyzePath = pathUtil.join(DIST_PATH, "analyze.txt");
    const mainBreakdownPath = pathUtil.join(DIST_PATH, "main-breakdown.md");

    await fsUtil.promises.writeFile(
        metafilePath,
        JSON.stringify(metafile, null, 2),
        "utf8",
    );
    await fsUtil.promises.writeFile(
        analyzePath,
        await esbuild.analyzeMetafile(metafile, { verbose: true }),
        "utf8",
    );

    const mainOutput = Object.entries(metafile.outputs).find(([filePath]) => {
        const normalizedPath = filePath.replace(/\\/g, "/");
        return normalizedPath.endsWith("/main.js") || normalizedPath === "main.js";
    });

    if (!mainOutput) {
        console.warn("Could not find main.js in esbuild metafile outputs.");
        return;
    }

    const [mainOutputPath, mainOutputInfo] = mainOutput;
    const rows = Object.entries(mainOutputInfo.inputs)
        .map(([inputPath, inputInfo]) => ({
            inputPath,
            bytes: inputInfo.bytesInOutput ?? 0,
        }))
        .sort((left, right) => right.bytes - left.bytes);

    const lines = [
        "# main.js Bundle Breakdown",
        "",
        `Output: \`${mainOutputPath}\``,
        `Total size: ${formatBytes(mainOutputInfo.bytes)}`,
        "",
        "| Rank | Size | Share | Module |",
        "| ---: | ---: | ---: | --- |",
        ...rows.map((row, index) => {
            const share = mainOutputInfo.bytes > 0
                ? `${((row.bytes / mainOutputInfo.bytes) * 100).toFixed(2)}%`
                : "0.00%";
            return `| ${index + 1} | ${formatBytes(row.bytes)} | ${share} | \`${row.inputPath}\` |`;
        }),
        "",
    ];

    await fsUtil.promises.writeFile(mainBreakdownPath, lines.join("\n"), "utf8");
    console.log(`Bundle metafile written to ${metafilePath}`);
    console.log(`Bundle analysis written to ${analyzePath}`);
    console.log(`main.js breakdown written to ${mainBreakdownPath}`);
}

async function removeStaleBundleAnalysis() {
    const analysisPaths = [
        pathUtil.join(DIST_PATH, "metafile.json"),
        pathUtil.join(DIST_PATH, "analyze.txt"),
        pathUtil.join(DIST_PATH, "main-breakdown.md"),
    ];
    for (const analysisPath of analysisPaths) {
        try {
            await fsUtil.promises.rm(analysisPath, { force: true });
        } catch (err) {
            console.warn(`Could not remove stale bundle analysis ${analysisPath}:`, err);
        }
    }
}

const DIST_PATH = "dist";
const DEV_COMMAND_REGISTRY_STUB_PATH = pathUtil.resolve(
    "src/services/obsidian/command-registry.noop.ts",
);
const DEV_DATA_MANAGER_STUB_PATH = pathUtil.resolve(
    "src/services/obsidian/user-data/data-manager.dev.noop.ts",
);
// 根据环境决定输出位置：生产环境去 dist，开发环境留根目录
const outDir = prod ? DIST_PATH : "./";

if (prod && !existsSync(DIST_PATH)) {
    mkdirSync(DIST_PATH, { recursive: true });
}

const esbuildConfig = {
    banner: {
        js: banner,
    },
    entryPoints: {
        main: "src/main.ts",
        "cs-search-worker": "src/web-workers/server.ts",
    },
    bundle: true,
    minify: prod,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins,
        "tests/*", // 不打包测试文件夹
    ],
    format: "cjs",
    platform: "node",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    metafile: analyzeBundle,
    treeShaking: true,
    outdir: outDir, 
    define: {
        "process.env.NODE_ENV": prod ? '"production"' : '"development"',
        __DEV__: prod ? "false" : "true",
    },
    plugins: [
        prod && {
            name: "alias-dev-only-modules",
            setup(build) {
                build.onResolve({ filter: /command-registry\.dev$/ }, () => {
                    return { path: DEV_COMMAND_REGISTRY_STUB_PATH };
                });
                build.onResolve({ filter: /data-manager\.dev$/ }, () => {
                    return { path: DEV_DATA_MANAGER_STUB_PATH };
                });
            },
        },
        esbuildSvelte({
            compilerOptions: { css: true },
            preprocess: sveltePreprocess(),
        }),
    ].filter(Boolean),
};

const context = await esbuild.context(esbuildConfig);

if (prod) {
    // 生产环境构建逻辑
    const result = await context.rebuild();
    if (analyzeBundle) {
        await writeBundleAnalysis(result.metafile);
    } else {
        await removeStaleBundleAnalysis();
    }
    
    // 自动将根目录的资源复制到 dist 文件夹，方便 GitHub Release 直接打包
    const filesToCopy = ["manifest.json", "styles.css"];
    for (const file of filesToCopy) {
        if (existsSync(file)) {
            copyFileSync(file, pathUtil.join(DIST_PATH, file));
            console.log(`📑 Copied ${file} to ${DIST_PATH}/`);
        }
    }

    await printFilesSize(DIST_PATH);
    await context.dispose();
    process.exit(0);
} else {
    // 开发环境：直接监听并生成到根目录
    console.log("\n🚀 Development mode: output to root");
    await context.watch();
}
